name: CICD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Cypress
      - name: Setup Cypress E2E tests
        uses: cypress-io/github-action@v6
        with:
          start: docker-compose up
          wait-on: "http://localhost:5173"

      # SonarQube
      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v7
        with: 
          start: docker-compose up
          wait-on: "http://localhost:9000"

      # Trivy
      - name: Setup Trivy
        uses: aquasecurity/trivy-action@0.30.0


      - name: Build and Run
        run: |
          docker build -t ecf-quizz .
          npx cypress open
          npx cypress run
          sonar-scanner
          trivy fs . --scanners vuln --severity HIGH,CRITICAL
